### ISSUE TITLE
Cannot read properties of undefined (reading 'localsInner')

### ISSUE THREAD

**Issue by zubweb** [gravity-ui/markdown-editor#409]
Добрый день. Не получается победить по человечески ошибку. Подскажите пожалуйста, люди добрые)

Cannot read properties of undefined (reading 'localsInner')
TypeError: Cannot read properties of undefined (reading 'localsInner')
    at DecorationGroup.locals (http://localhost:8200/static/js/bundle.js:331905:36)
    at iterDeco (http://localhost:8200/static/js/bundle.js:329928:21)
    at NodeViewDesc.updateChildren (http://localhost:8200/static/js/bundle.js:329312:5)
    at docViewDesc (http://localhost:8200/static/js/bundle.js:329433:35)
    at new EditorView (http://localhost:8200/static/js/bundle.js:332860:20)
    at new WysiwygEditor (http://localhost:8200/static/js/bundle.js:34957:94)
    at get wysiwygEditor (http://localhost:8200/static/js/bundle.js:30597:102)
    at get actions (http://localhost:8200/static/js/bundle.js:30655:17)
    at isEnable (http://localhost:8200/static/js/bundle.js:32432:20)
![Снимок экрана от 2024-10-09 13-18-45](https://github.com/user-attachments/assets/0e337eec-a3fd-4a19-9b42-03a6b5ae4487)

    at http://localhost:8200/static/js/bundle.js:62310:23

**Comment by zubweb** [comment]
По итогу страданий стало понятно. Менять npm install на yarn add в данном случае не стоит. нпм видимо чего т ещё доставляет.

**Comment by makhnatkin** [comment]
@zubweb правильно я понимаю, что проблема решилась после того как были добавлены недостающие элементы тулбара?

**Comment by zubweb** [comment]
Да, спасибо.

вт, 4 мар. 2025 г. в 18:17, Sergey Makhnatkin ***@***.***>:
